[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Kenzie Jeanis <isavegas2006@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
lazy_static = "1.4.0"
permutohedron = "0.2.4"
